### ISSUE TITLE
I can't find the data.mat in the project

### ISSUE THREAD

**Issue by SEU-Lai** [Xiaoyang-Rebecca/PatternRecognition_Matlab#2]
I can't find the data.mat in the project,so that the project can't work .Can you provide the data to me,thanks

**Comment by FaiqMadani** [comment]
exactly, we need "data.mat" to run the project

**Comment by Xiaoyang-Rebecca** [comment]
Upload it here:
https://github.com/Xiaoyang-Rebecca/PatternRecognition_Matlab/blob/master/data.mat
